language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
script: npm test
deploy:
  provider: elasticbeanstalk
  edge: true
  access_key_id: AKIAJR5G53S6P2HFMPXA
  secret_access_key:
    secure: V7ZL4Jk4VVcX8heqhyrTo8qvo0VtLDuVyb7OQ7WV/EPY0KpzyItzElSBIS4OieyHsZZT7k9blAj3JczBWXX3XctCzFOIZChF48zufcUcr8NLncuh/Moz/QL40yzXVlKBgKYoh+o+1/9t55y/JfF6JrHpWtGRFw+S1oADrmaXKK4=
  app: Interactive Events API
  env: Production
  region: eu-west-1
  skip_cleanup: true
  bucket_name: interactive-events-api-deploy
  on:
    branch: release
before_install:
- openssl aes-256-cbc -K $encrypted_f97b212754ab_key -iv $encrypted_f97b212754ab_iv
  -in secret.js.enc -out secret.js -d
